import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:geolocator/geolocator.dart';
import 'dart:async';
import 'package:intl/intl.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shared_preferences/shared_preferences.dart';
// ADDED IMPORT: This links to the file generated by flutterfire configure
import 'package:calm_weather/firebase_options.dart';

// ------------------------------------
// NEW: Authentication Service using Firestore and SharedPreferences
// ------------------------------------
class AuthService {
  final StreamController<bool> _authStateController =
      StreamController<bool>.broadcast();
  Stream<bool> get authStateChanges => _authStateController.stream;

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final String _collectionName = 'users'; // Firestore collection name
  final String _prefsKey = 'isLoggedIn'; // SharedPreferences key

  AuthService() {
    _checkInitialLoginStatus();
  }

  void _checkInitialLoginStatus() async {
    final prefs = await SharedPreferences.getInstance();
    final isLoggedIn = prefs.getBool(_prefsKey) ?? false;
    _authStateController.add(isLoggedIn);
  }

  Future<void> signUp(String email, String password) async {
    // 1. Check if user already exists
    final result = await _firestore
        .collection(_collectionName)
        .doc(email)
        .get();
    if (result.exists) {
      throw 'Account already exists for this email.';
    }

    // 2. Create the account (only store email and password placeholder)
    // NOTE: In production, password_hash should use proper hashing (e.g., bcrypt)
    await _firestore.collection(_collectionName).doc(email).set({
      'email': email,
      'password_hash': password.hashCode, // Mock password hash
      'created_at': FieldValue.serverTimestamp(),
    });

    // 3. Log the user in after successful registration
    await _storeLoginState(true, email);
    _authStateController.add(true);
  }

  Future<void> signIn(String email, String password) async {
    // 1. Check credentials (Mock validation against stored hash)
    final userDoc = await _firestore
        .collection(_collectionName)
        .doc(email)
        .get();

    if (!userDoc.exists || userDoc['password_hash'] != password.hashCode) {
      throw 'Invalid email or password.';
    }

    // 2. Store login state and transition
    await _storeLoginState(true, email);
    _authStateController.add(true);
  }

  Future<void> signOut() async {
    await _storeLoginState(false, null);
    _authStateController.add(false);
  }

  Future<void> _storeLoginState(bool isLoggedIn, String? email) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_prefsKey, isLoggedIn);
    if (email != null) {
      await prefs.setString('userEmail', email); // Save email for autofill
    } else {
      await prefs.remove('userEmail');
    }
  }

  Future<String?> getLastEmail() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString('userEmail');
  }

  void dispose() {
    _authStateController.close();
  }
}
// ------------------------------------

final AuthService _authService = AuthService();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // FIX 1: Initialization is outside the declaration block and uses the generated options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const WeatherApp());
}

class WeatherApp extends StatelessWidget {
  const WeatherApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Calm Weather', // Renamed app title
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blueGrey,
        fontFamily: 'Inter',
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: StreamBuilder<bool>(
        initialData: false,
        stream: _authService.authStateChanges,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.active ||
              snapshot.hasData) {
            final isLoggedIn = snapshot.data!;
            if (isLoggedIn) {
              return const WeatherScreen();
            } else {
              // The AuthScreen manages the switch between Login and Sign Up tabs
              return const AuthScreen();
            }
          }
          // Initial loading screen while checking auth state
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
            backgroundColor: Color(0xFF88A9C3),
          );
        },
      ),
    );
  }
}

// ------------------------------------
// NEW: AuthScreen (Manages Login/Sign Up Tabs)
// ------------------------------------
class AuthScreen extends StatefulWidget {
  const AuthScreen({super.key});

  @override
  State<AuthScreen> createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  // 0 = Login, 1 = Sign Up
  int _selectedIndex = 0;

  // --- Calm Color Palette ---
  static const Color _calmStartBlue = Color(0xFF88A9C3);
  static const Color _calmEndBlue = Color(0xFFC7D7E3);
  static const Color _calmAccentTeal = Color(0xFF5B9B9D);
  static const Color _calmPrimaryTextColor = Color(0xFF333D47);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [_calmStartBlue, _calmEndBlue],
          ),
        ),
        child: Center(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(32.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Title
                Center(
                  child: Text(
                    _selectedIndex == 0 ? 'Welcome Back' : 'Create Account',
                    style: const TextStyle(
                      fontSize: 32,
                      fontWeight: FontWeight.w900,
                      color: Colors.white,
                      letterSpacing: 1.5,
                    ),
                  ),
                ),
                const SizedBox(height: 40),

                // Tab Content Switch
                _selectedIndex == 0
                    ? const LoginScreen()
                    : const SignUpScreen(),

                const SizedBox(height: 30),

                // Switch Tab Link (Login <-> Sign Up)
                TextButton(
                  onPressed: () {
                    setState(() {
                      _selectedIndex = _selectedIndex == 0 ? 1 : 0;
                    });
                  },
                  child: Text(
                    _selectedIndex == 0
                        ? "Don't have an account? Sign Up"
                        : "Already have an account? Login",
                    style: TextStyle(
                      color: _calmPrimaryTextColor,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// ------------------------------------
// NEW: Login Screen Component
// ------------------------------------
class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  // FIX 2: Controllers are now defined in the State class
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();

  // NEW: State for password visibility toggle
  bool _isPasswordVisible = false;

  bool _isLoading = false;
  String? _error;

  static const Color _calmAccentTeal = Color(0xFF5B9B9D);
  static const Color _calmDarkBlue = Color(0xFF4C7B8F);
  static const Color _calmPrimaryTextColor = Color(0xFF333D47);

  @override
  void initState() {
    super.initState();
    _loadLastEmail();
  }

  void _loadLastEmail() async {
    final email = await _authService.getLastEmail();
    if (email != null && mounted) {
      _emailController.text = email;
    }
  }

  Future<void> _login() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      await _authService.signIn(
        _emailController.text,
        _passwordController.text,
      );
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = e.toString();
          _isLoading = false;
        });
      }
    }
  }

  // Helper for forgotten password flow (3-step modal)
  void _showForgotPasswordFlow(BuildContext context) {
    String stepError = '';
    // Controllers for the modal steps are defined locally inside the function
    TextEditingController emailResetController = TextEditingController(
      text: _emailController.text,
    );
    TextEditingController codeController = TextEditingController();
    TextEditingController newPasswordController = TextEditingController();

    // Simulates sending a code to the email
    void sendCode() {
      if (!emailResetController.text.endsWith('@gmail.com')) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Error: Email must end with @gmail.com.'),
          ),
        );
      } else {
        Navigator.of(context).pop();
        _showCodeInput(
          context,
          emailResetController.text,
          codeController,
          newPasswordController,
        );
      }
    }

    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text("Reset Password (Step 1/3)"),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              const Text(
                "Enter your email address to receive a verification code.",
              ),
              const SizedBox(height: 16),
              TextField(
                controller: emailResetController,
                keyboardType: TextInputType.emailAddress,
                decoration: _buildInputDecoration(
                  'Email',
                  Icons.email_outlined,
                ),
              ),
              if (stepError.isNotEmpty)
                Text(stepError, style: const TextStyle(color: Colors.red)),
            ],
          ),
          actions: <Widget>[
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text('Cancel'),
            ),
            ElevatedButton(onPressed: sendCode, child: const Text('Send Code')),
          ],
        );
      },
    );
  }

  // Step 2: Code Input
  void _showCodeInput(
    BuildContext context,
    String email,
    TextEditingController codeController,
    TextEditingController newPasswordController,
  ) {
    String stepError = '';

    void verifyCode() {
      if (codeController.text != '123456') {
        // Mock verification code
        // Update error locally (state outside widget is unnecessary here)
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Invalid code. Use 123456.')),
        );
      } else {
        Navigator.of(context).pop();
        _showNewPasswordInput(context, email, newPasswordController);
      }
    }

    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text("Reset Password (Step 2/3)"),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Text(
                "A code has been sent to $email. Enter it below (Mock: 123456).",
              ),
              const SizedBox(height: 16),
              TextField(
                controller: codeController,
                keyboardType: TextInputType.number,
                decoration: _buildInputDecoration(
                  'Verification Code',
                  Icons.lock_open_outlined,
                ),
              ),
              if (stepError.isNotEmpty)
                Text(stepError, style: const TextStyle(color: Colors.red)),
            ],
          ),
          actions: <Widget>[
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text('Cancel'),
            ),
            ElevatedButton(onPressed: verifyCode, child: const Text('Verify')),
          ],
        );
      },
    );
  }

  // Step 3: New Password Input
  void _showNewPasswordInput(
    BuildContext context,
    String email,
    TextEditingController newPasswordController,
  ) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text("Reset Password (Step 3/3)"),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              const Text("Enter and confirm your new password."),
              const SizedBox(height: 16),
              TextField(
                controller: newPasswordController,
                obscureText: true,
                decoration: _buildInputDecoration(
                  'New Password',
                  Icons.vpn_key_outlined,
                ),
              ),
            ],
          ),
          actions: <Widget>[
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text('Cancel'),
            ),
            ElevatedButton(
              onPressed: () {
                // Mock password update succeeded
                Navigator.of(context).pop();
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Password successfully updated!'),
                  ),
                );
              },
              child: const Text('Set New Password'),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // Email Field (Autofills last logged-in user's email)
        TextField(
          controller: _emailController,
          keyboardType: TextInputType.emailAddress,
          style: TextStyle(color: _calmPrimaryTextColor),
          decoration: _buildInputDecoration('Email', Icons.email_outlined),
        ),
        const SizedBox(height: 20),

        // Password Field with Visibility Toggle
        TextField(
          controller: _passwordController,
          obscureText: !_isPasswordVisible, // Toggled by state
          style: TextStyle(color: _calmPrimaryTextColor),
          decoration: _buildInputDecoration(
            'Password',
            Icons.lock_outline,
            suffixIcon: IconButton(
              icon: Icon(
                _isPasswordVisible ? Icons.visibility : Icons.visibility_off,
                color: _calmDarkBlue.withOpacity(0.6),
              ),
              onPressed: () {
                setState(() {
                  _isPasswordVisible = !_isPasswordVisible;
                });
              },
            ),
          ),
        ),
        const SizedBox(height: 10),

        // Forgot Password Link
        Align(
          alignment: Alignment.centerRight,
          child: TextButton(
            onPressed: () => _showForgotPasswordFlow(context),
            child: Text(
              'Forgot Password?',
              style: TextStyle(
                color: _calmDarkBlue,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ),
        const SizedBox(height: 30),

        // Error Display
        if (_error != null)
          Padding(
            padding: const EdgeInsets.only(bottom: 20.0),
            child: Text(
              _error!,
              textAlign: TextAlign.center,
              style: const TextStyle(
                color: Colors.redAccent,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),

        // Login Button
        ElevatedButton(
          onPressed: _isLoading ? null : _login,
          style: ElevatedButton.styleFrom(
            backgroundColor: _calmAccentTeal, // Calm accent color
            padding: const EdgeInsets.symmetric(vertical: 18),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
            elevation: 5,
          ),
          child: _isLoading
              ? const SizedBox(
                  width: 24,
                  height: 24,
                  child: CircularProgressIndicator(
                    color: Colors.white,
                    strokeWidth: 3,
                  ),
                )
              : const Text(
                  'LOGIN',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
        ),
      ],
    );
  }
}

// ------------------------------------
// NEW: Sign Up Screen Component (with validation)
// ------------------------------------
class SignUpScreen extends StatefulWidget {
  const SignUpScreen({super.key});

  @override
  State<SignUpScreen> createState() => _SignUpScreenState();
}

class _SignUpScreenState extends State<SignUpScreen> {
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();

  // NEW: State for password visibility toggle
  bool _isPasswordVisible = false;

  bool _isLoading = false;
  String? _error;

  static const Color _calmAccentTeal = Color(0xFF5B9B9D);
  static const Color _calmDarkBlue = Color(0xFF4C7B8F);
  static const Color _calmPrimaryTextColor = Color(0xFF333D47);

  Future<void> _signUp() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    final email = _emailController.text.trim();
    final password = _passwordController.text;

    // --- Validation Checks ---
    if (!email.endsWith('@gmail.com')) {
      return _showError('Email must end with @gmail.com only.');
    }
    if (password.length < 8) {
      return _showError('Password must be at least 8 characters.');
    }
    if (!password.contains(RegExp(r'[A-Z]'))) {
      return _showError('Password must contain at least one uppercase letter.');
    }
    if (!password.contains(RegExp(r'[0-9]'))) {
      return _showError('Password must contain at least one number.');
    }
    if (!password.contains(RegExp(r'[!@#$%^&*(),.?":{}|<>]'))) {
      return _showError(
        'Password must contain at least one special character.',
      );
    }
    // --- End Validation Checks ---

    try {
      await _authService.signUp(email, password);
    } catch (e) {
      _showError(e.toString());
    }
  }

  void _showError(String message) {
    if (mounted) {
      setState(() {
        _error = message;
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // Email Field
        TextField(
          controller: _emailController,
          keyboardType: TextInputType.emailAddress,
          style: TextStyle(color: _calmPrimaryTextColor),
          decoration: _buildInputDecoration(
            'Email (Must end with @gmail.com)',
            Icons.email_outlined,
          ),
        ),
        const SizedBox(height: 20),

        // Password Field with Visibility Toggle
        TextField(
          controller: _passwordController,
          obscureText: !_isPasswordVisible, // Toggled by state
          style: TextStyle(color: _calmPrimaryTextColor),
          decoration: _buildInputDecoration(
            'Password (Min 8, U/C, #, Symbol)',
            Icons.lock_outline,
            suffixIcon: IconButton(
              icon: Icon(
                _isPasswordVisible ? Icons.visibility : Icons.visibility_off,
                color: _calmDarkBlue.withOpacity(0.6),
              ),
              onPressed: () {
                setState(() {
                  _isPasswordVisible = !_isPasswordVisible;
                });
              },
            ),
          ),
        ),
        const SizedBox(height: 10),

        // Validation Hint
        const Padding(
          padding: EdgeInsets.only(bottom: 20.0),
          child: Text(
            'Password requires 8+ chars, Uppercase, Number, and Symbol.',
            style: TextStyle(color: Colors.white70, fontSize: 12),
          ),
        ),

        // Error Display
        if (_error != null)
          Padding(
            padding: const EdgeInsets.only(bottom: 20.0),
            child: Text(
              _error!,
              textAlign: TextAlign.center,
              style: const TextStyle(
                color: Colors.redAccent,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),

        // Sign Up Button
        ElevatedButton(
          onPressed: _isLoading ? null : _signUp,
          style: ElevatedButton.styleFrom(
            backgroundColor: _calmAccentTeal, // Calm accent color
            padding: const EdgeInsets.symmetric(vertical: 18),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
            elevation: 5,
          ),
          child: _isLoading
              ? const SizedBox(
                  width: 24,
                  height: 24,
                  child: CircularProgressIndicator(
                    color: Colors.white,
                    strokeWidth: 3,
                  ),
                )
              : const Text(
                  'SIGN UP',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
        ),
      ],
    );
  }
}

// Helper for consistent input styling (Used by Login, Sign Up, Forgot Password)
InputDecoration _buildInputDecoration(
  String label,
  IconData icon, {
  Widget? suffixIcon,
}) {
  const Color _calmAccentTeal = Color(0xFF5B9B9D);
  const Color _calmDarkBlue = Color(0xFF4C7B8F);
  const Color _calmPrimaryTextColor = Color(0xFF333D47);

  return InputDecoration(
    labelText: label,
    labelStyle: TextStyle(color: _calmPrimaryTextColor.withOpacity(0.7)),
    filled: true,
    fillColor: Colors.white.withOpacity(0.85),
    prefixIcon: Icon(icon, color: _calmDarkBlue),
    suffixIcon: suffixIcon, // Added optional suffix icon support
    contentPadding: const EdgeInsets.symmetric(vertical: 18, horizontal: 15),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(10),
      borderSide: BorderSide(color: Colors.white.withOpacity(0.2), width: 1),
    ),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(10),
      borderSide: BorderSide(color: Colors.white.withOpacity(0.4), width: 1),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(10),
      borderSide: const BorderSide(color: _calmAccentTeal, width: 2),
    ),
  );
}

// ------------------------------------
// START: Weather Screen (Main Application Content)
// ------------------------------------

class WeatherScreen extends StatefulWidget {
  const WeatherScreen({super.key});

  @override
  State<WeatherScreen> createState() => _WeatherScreenState();
}

class _WeatherScreenState extends State<WeatherScreen> {
  Map<String, dynamic>? _weatherData;
  List<dynamic>? _dailyForecast; // NEW: Store daily forecast data
  String _locationName = "Detecting Location...";
  bool _isLoading = false;
  String? _error;
  DateTime _currentTime = DateTime.now();
  late Timer _timer;

  // New state for search functionality
  bool _isSearching = false;
  final TextEditingController _searchController = TextEditingController();

  // --- Calm Color Palette ---
  static const Color _calmStartBlue = Color(0xFF88A9C3); // Soft blue/gray
  static const Color _calmEndBlue = Color(0xFFC7D7E3); // Very light, cool blue
  static const Color _calmAccentTeal = Color(
    0xFF5B9B9D,
  ); // Muted Teal/Blue for buttons/icons
  static const Color _calmIconYellow = Color(
    0xFFFFDAA3,
  ); // Soft Pale Gold for sun/brightness
  static const Color _calmDarkBlue = Color(
    0xFF4C7B8F,
  ); // Darker muted blue-green for contrast

  @override
  void initState() {
    super.initState();
    _startClock();
    _handleLocationClick();
  }

  @override
  void dispose() {
    _timer.cancel();
    _searchController.dispose();
    super.dispose();
  }

  // Starts the clock timer
  void _startClock() {
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (mounted) {
        setState(() {
          _currentTime = DateTime.now();
        });
      }
    });
  }

  // Toggles the search input field visibility
  void _toggleSearch() {
    setState(() {
      _isSearching = !_isSearching;
      if (!_isSearching) {
        _searchController.clear();
        _error = null; // Clear error when closing search
      }
    });
  }

  // --- Location and Weather Logic ---

  Future<void> _handleLocationClick() async {
    setState(() {
      _isLoading = true;
      _error = null;
      _locationName = "Locating...";
    });

    try {
      final position = await _determinePosition();
      await _fetchWeather(
        position.latitude,
        position.longitude,
        isGeolocation: true,
      );
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = e.toString();
          _isLoading = false;
          _locationName = "Location Denied";
        });
      }
    }
  }

  Future<void> _handleCitySearch(String city) async {
    if (city.trim().isEmpty) return;

    setState(() {
      _isLoading = true;
      _error = null;
      _locationName = "Searching for $city...";
    });

    // Forward Geocoding using Nominatim
    try {
      final response = await http.get(
        Uri.parse(
          'https://nominatim.openstreetmap.org/search?q=${Uri.encodeComponent(city)}}&format=json&limit=1',
        ),
      );

      if (response.statusCode == 200) {
        final List results = json.decode(response.body);
        if (results.isNotEmpty) {
          final lat = double.parse(results[0]['lat']);
          final lon = double.parse(results[0]['lon']);

          await _fetchWeather(lat, lon);

          // After successful search, close the search bar
          if (mounted) _toggleSearch();
        } else {
          throw 'City not found: $city';
        }
      } else {
        throw 'Failed to connect to search service.';
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = 'Search failed: ${e.toString()}';
          _isLoading = false;
          _locationName = "Search Error";
        });
      }
    }
  }

  /// Determines the current position of the device.
  Future<Position> _determinePosition() async {
    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      throw 'Location services are disabled.';
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        throw 'Location permissions are denied.';
      }
    }

    if (permission == LocationPermission.deniedForever) {
      throw 'Location permissions are permanently denied. Please enable them in settings.';
    }

    return await Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.low,
    );
  }

  /// Fetches a human-readable location name using reverse geocoding.
  Future<void> _fetchLocationName(
    double lat,
    double lon, {
    bool isGeolocation = false,
  }) async {
    // If the location was found via search, we already have a clean city name.
    if (!isGeolocation && _locationName.startsWith('Searching')) {
      return;
    }

    try {
      // Using OpenStreetMap Nominatim for reverse geocoding (free, no key)
      final response = await http.get(
        Uri.parse(
          'https://nominatim.openstreetmap.org/reverse?format=json&lat=$lat&lon=$lon',
        ),
      );

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        final address = data['address'] ?? {};

        final city =
            address['city'] ??
            address['town'] ??
            address['village'] ??
            address['county'] ??
            "Unknown Location";
        if (mounted) {
          setState(() {
            _locationName = city;
          });
        }
      } else {
        // Fallback to coordinates on API failure
        if (mounted) {
          setState(() {
            _locationName =
                '${lat.toStringAsFixed(2)}, ${lon.toStringAsFixed(2)}';
          });
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _locationName =
              '${lat.toStringAsFixed(2)}, ${lon.toStringAsFixed(2)}';
        });
      }
      print("Failed to get city name: $e");
    }
  }

  /// Fetches weather data from Open-Meteo, including current and daily forecast.
  Future<void> _fetchWeather(
    double lat,
    double lon, {
    bool isGeolocation = false,
  }) async {
    try {
      // UPDATED API CALL: Added 'daily=...' for 5-day forecast
      final url = Uri.parse(
        'https://api.open-meteo.com/v1/forecast?latitude=$lat&longitude=$lon&current=temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,weather_code,cloud_cover,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min&forecast_days=5&timezone=auto',
      );

      final response = await http.get(url);

      if (response.statusCode == 200) {
        final data = json.decode(response.body);

        // Process daily forecast data
        List<Map<String, dynamic>> dailyData = [];
        final daily = data['daily'];

        if (daily != null) {
          // The API returns arrays for each parameter (time, max temp, min temp, etc.)
          for (int i = 0; i < daily['time'].length; i++) {
            dailyData.add({
              'time': daily['time'][i],
              'weather_code': daily['weather_code'][i],
              'temperature_2m_max': daily['temperature_2m_max'][i].round(),
              'temperature_2m_min': daily['temperature_2m_min'][i].round(),
            });
          }
        }

        if (mounted) {
          setState(() {
            _weatherData = data['current'];
            _dailyForecast = dailyData; // Store the processed daily data
            _isLoading = false;
          });
          _fetchLocationName(
            lat,
            lon,
            isGeolocation: isGeolocation,
          ); // Fetch location name after weather data
        }
      } else {
        throw 'Failed to load weather data with status: ${response.statusCode}';
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = 'Unable to fetch weather data: $e';
          _isLoading = false;
        });
      }
    }
  }

  // --- Utility Functions for UI ---

  // Converts WMO code to an appropriate icon
  IconData _getWeatherIcon(int code, int isDay) {
    bool day = isDay == 1;
    switch (code) {
      case 0:
        return day ? Icons.wb_sunny : Icons.nights_stay;
      case 1:
      case 2:
      case 3:
        return day ? Icons.cloud : Icons.cloud_queue;
      case 45:
      case 48:
        return Icons.cloudy_snowing;
      case 51:
      case 53:
      case 55:
      case 61:
      case 63:
      case 65:
        return Icons.cloudy_snowing;
      case 71:
      case 73:
      case 75:
      case 77:
        return Icons.ac_unit;
      case 80:
      case 81:
      case 82:
        return Icons.beach_access; // Rain showers
      case 95:
      case 96:
      case 99:
        return Icons.thunderstorm;
      default:
        return day ? Icons.wb_sunny : Icons.nights_stay;
    }
  }

  // Converts WMO code to a description string
  String _getWeatherDescription(int code) {
    const Map<int, String> codes = {
      0: "Clear Sky",
      1: "Mainly Clear",
      2: "Partly Cloudy",
      3: "Overcast",
      45: "Foggy",
      48: "Rime Fog",
      51: "Light Drizzle",
      53: "Moderate Drizzle",
      55: "Dense Drizzle",
      61: "Slight Rain",
      63: "Moderate Rain",
      65: "Heavy Rain",
      71: "Slight Snow",
      73: "Moderate Snow",
      75: "Heavy Snow",
      95: "Thunderstorm",
      96: "Thunderstorm & Hail",
    };
    return codes[code] ?? "Unknown";
  }

  // --- UI Builder Methods ---

  @override
  Widget build(BuildContext context) {
    final weather = _weatherData;
    final int temp = weather != null
        ? weather['temperature_2m']?.round() ?? 0
        : 0;
    final int windSpeed = weather != null
        ? weather['wind_speed_10m']?.round() ?? 0
        : 0;
    final int humidity = weather != null
        ? weather['relative_humidity_2m']?.round() ?? 0
        : 0;
    final int feelsLike = weather != null
        ? weather['apparent_temperature']?.round() ?? 0
        : 0;
    final int weatherCode = weather != null ? weather['weather_code'] ?? 0 : 0;
    final int isDay = weather != null ? weather['is_day'] ?? 1 : 1;

    final DateFormat timeFormat = DateFormat('hh:mm a');
    final DateFormat dateFormat = DateFormat('EEE, d MMM');

    return Scaffold(
      body: Stack(
        children: [
          // Background Gradient (CALM COLORS)
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                colors: [_calmStartBlue, _calmEndBlue],
              ),
            ),
          ),

          // Main Content
          SafeArea(
            child: SingleChildScrollView(
              // Allow scrolling for the new forecast section
              padding: const EdgeInsets.all(24.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Header (Location & Time) OR Search Bar
                  AnimatedSwitcher(
                    duration: const Duration(milliseconds: 300),
                    child: _isSearching
                        ? _buildSearchBar()
                        : _buildHeader(timeFormat.format(_currentTime)),
                  ),
                  const SizedBox(height: 16), // Spacing after header
                  // Current Weather Section (Central)
                  SizedBox(
                    height:
                        MediaQuery.of(context).size.height *
                        0.6, // Allocate space for current weather
                    child: Center(
                      child: _buildBody(
                        temp,
                        windSpeed,
                        humidity,
                        feelsLike,
                        weatherCode,
                        isDay,
                        dateFormat.format(_currentTime),
                      ),
                    ),
                  ),

                  // Daily Forecast Section (NEW)
                  if (_dailyForecast != null && _weatherData != null)
                    _buildDailyForecast(),
                ],
              ),
            ),
          ),
        ],
      ),
      // Floating Action Buttons for Location and Search
      floatingActionButton: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Logout Button
          FloatingActionButton(
            onPressed: () {
              // Sign out the user
              _authService.signOut();
            },
            heroTag: 'logoutBtn',
            backgroundColor: Colors.redAccent,
            elevation: 8,
            shape: const CircleBorder(),
            child: const Icon(Icons.logout, color: Colors.white, size: 24),
          ),
          const SizedBox(height: 16),

          // Search Button
          FloatingActionButton(
            onPressed: _toggleSearch,
            heroTag: 'searchBtn',
            backgroundColor: _isSearching ? Colors.redAccent : _calmAccentTeal,
            elevation: 8,
            shape: const CircleBorder(),
            child: Icon(
              _isSearching ? Icons.close : Icons.search,
              color: Colors.white,
              size: 24,
            ),
          ),
          const SizedBox(height: 16),
          // Location Button (Existing)
          FloatingActionButton(
            onPressed: _isLoading ? null : _handleLocationClick,
            heroTag: 'locationBtn',
            backgroundColor: _calmAccentTeal,
            elevation: 8,
            shape: const CircleBorder(),
            child: _isLoading && !_isSearching
                ? const SizedBox(
                    width: 24,
                    height: 24,
                    child: CircularProgressIndicator(
                      strokeWidth: 3,
                      color: Colors.white,
                    ),
                  )
                : const Icon(Icons.my_location, color: Colors.white, size: 24),
          ),
        ],
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.endFloat,
    );
  }

  Widget _buildHeader(String timeString) {
    return Row(
      key: const ValueKey('header'),
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        // Location Chip
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
          decoration: BoxDecoration(
            color: Colors.black.withOpacity(0.1),
            borderRadius: BorderRadius.circular(30),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.location_on, size: 16, color: Colors.white),
              const SizedBox(width: 6),
              Text(
                _locationName,
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 13,
                  fontWeight: FontWeight.w500,
                ),
              ),
            ],
          ),
        ),
        // Time Display
        Row(
          children: [
            const Icon(Icons.access_time, size: 16, color: Colors.white),
            const SizedBox(width: 6),
            Text(
              timeString,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 13,
                fontWeight: FontWeight.w500,
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildSearchBar() {
    return Container(
      key: const ValueKey('search'),
      height: 50,
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.9),
        borderRadius: BorderRadius.circular(30),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 10,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: TextField(
        controller: _searchController,
        autofocus: true,
        textInputAction: TextInputAction.search,
        onSubmitted: (value) => _handleCitySearch(value),
        style: TextStyle(color: _calmDarkBlue),
        decoration: InputDecoration(
          hintText: 'Search city...',
          hintStyle: TextStyle(color: _calmDarkBlue.withOpacity(0.6)),
          border: InputBorder.none,
          prefixIcon: Icon(Icons.search, color: _calmDarkBlue),
          suffixIcon: IconButton(
            icon: Icon(Icons.clear, color: _calmDarkBlue.withOpacity(0.6)),
            onPressed: () {
              _searchController.clear();
            },
          ),
          contentPadding: const EdgeInsets.symmetric(vertical: 15),
        ),
      ),
    );
  }

  Widget _buildBody(
    int temp,
    int windSpeed,
    int humidity,
    int feelsLike,
    int weatherCode,
    int isDay,
    String dateString,
  ) {
    if (_error != null) {
      return _buildErrorWidget();
    }

    if (_isLoading || _weatherData == null) {
      return _buildLoadingWidget();
    }

    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        // Date Chip
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          decoration: BoxDecoration(
            color: Colors.black.withOpacity(
              0.1,
            ), // Darker background for light theme
            borderRadius: BorderRadius.circular(30),
            border: Border.all(color: Colors.white.withOpacity(0.2)),
          ),
          child: Text(
            dateString,
            style: const TextStyle(
              color: Colors.white,
              fontSize: 14,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        const SizedBox(height: 32),

        // Main Icon (CALM ICON YELLOW)
        Icon(
          _getWeatherIcon(weatherCode, isDay),
          color: _calmIconYellow,
          size: 100,
        ),
        const SizedBox(height: 24),

        // Temperature
        Text(
          '$temp°',
          style: TextStyle(
            fontSize: 80,
            fontWeight: FontWeight.bold,
            foreground: Paint()
              ..shader = const LinearGradient(
                colors: <Color>[
                  Colors.white,
                  Color(0xFFF0F4F7),
                ], // Lighter gradient for softer background
              ).createShader(const Rect.fromLTWH(0.0, 0.0, 200.0, 70.0)),
          ),
        ),
        const SizedBox(height: 8),

        // Description
        Text(
          _getWeatherDescription(weatherCode),
          style: const TextStyle(
            color: Colors.white,
            fontSize: 22,
            fontWeight: FontWeight.w500,
          ),
        ),
        const SizedBox(height: 4),

        // Feels Like
        Text(
          'Feels like $feelsLike°',
          style: const TextStyle(color: Colors.white70, fontSize: 16),
        ),
        const SizedBox(height: 40),

        // Grid Stats
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _buildStatCard(
              icon: Icons.air,
              iconColor: _calmAccentTeal, // New calm accent
              label: 'Wind',
              value: '$windSpeed km/h',
            ),
            const SizedBox(width: 20),
            _buildStatCard(
              icon: Icons.opacity,
              iconColor: _calmDarkBlue, // Darker calm blue
              label: 'Humidity',
              value: '$humidity%',
            ),
          ],
        ),
        // Spacer to push current weather section up slightly
        const SizedBox(height: 30),
      ],
    );
  }

  Widget _buildLoadingWidget() {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        SizedBox(
          width: 50,
          height: 50,
          child: CircularProgressIndicator(
            valueColor: AlwaysStoppedAnimation<Color>(
              _calmAccentTeal,
            ), // New calm accent
            strokeWidth: 4.0,
          ),
        ),
        const SizedBox(height: 16),
        Text(
          _locationName,
          style: const TextStyle(color: Colors.white70, fontSize: 16),
        ),
      ],
    );
  }

  Widget _buildErrorWidget() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.red.withOpacity(0.2),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.red.withOpacity(0.3)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            _error!,
            textAlign: TextAlign.center,
            style: const TextStyle(color: Colors.white, fontSize: 16),
          ),
          const SizedBox(height: 16),
          ElevatedButton(
            onPressed: _handleLocationClick,
            style: ElevatedButton.styleFrom(
              backgroundColor:
                  _calmDarkBlue, // Used a dark calm color for the button
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
            child: const Text(
              'Retry Location',
              style: TextStyle(color: Colors.white),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildStatCard({
    required IconData icon,
    required Color iconColor,
    required String label,
    required String value,
  }) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.black.withOpacity(0.1), // Soft dark overlay
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: Colors.white.withOpacity(0.05)),
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: iconColor.withOpacity(0.2),
                borderRadius: BorderRadius.circular(50),
              ),
              child: Icon(icon, size: 24, color: iconColor),
            ),
            const SizedBox(width: 12),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label.toUpperCase(),
                  style: const TextStyle(
                    color: Colors.white70,
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                    letterSpacing: 0.5,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  value,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  // --- NEW: Daily Forecast Widget ---
  Widget _buildDailyForecast() {
    if (_dailyForecast == null || _dailyForecast!.isEmpty)
      return const SizedBox.shrink();

    // Skip the first day since it's the current day (covered by the main screen)
    final forecastList = _dailyForecast!.skip(1).toList();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Padding(
          padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
          child: Text(
            '5-Day Forecast',
            style: TextStyle(
              color: Colors.white,
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
        // ListView.builder embedded in a fixed height container
        SizedBox(
          height: 120,
          child: ListView.builder(
            scrollDirection: Axis.horizontal,
            itemCount: forecastList.length,
            itemBuilder: (context, index) {
              final day = forecastList[index];
              final DateTime date = DateTime.parse(day['time']);
              final String dayOfWeek = DateFormat('EEE').format(date);
              final int maxTemp = day['temperature_2m_max'];
              final int minTemp = day['temperature_2m_min'];
              final int weatherCode = day['weather_code'];

              return Padding(
                padding: const EdgeInsets.only(right: 12.0),
                child: Container(
                  width: 90,
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.15),
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: Colors.white.withOpacity(0.05)),
                  ),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.spaceAround,
                    children: [
                      Text(
                        dayOfWeek,
                        style: const TextStyle(
                          color: Colors.white70,
                          fontSize: 14,
                        ),
                      ),
                      Icon(
                        _getWeatherIcon(
                          weatherCode,
                          1,
                        ), // Assume daytime icon for forecast summary
                        color: _calmIconYellow.withOpacity(0.8),
                        size: 32,
                      ),
                      Text(
                        '$maxTemp° / $minTemp°',
                        style: const TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.w600,
                          fontSize: 16,
                        ),
                      ),
                    ],
                  ),
                ),
              );
            },
          ),
        ),
      ],
    );
  }
}
